import Head from 'next/head'
import Layout from '../components/Layout'
import '../styles/globals.css'

function MyApp({ Component, pageProps }) {
	return ( 
		<>
			<Head>
				<title>Gurshan Jhinger</title>
				<meta charset="UTF-8" />
				<meta name="description" content="Generated by create next app" />
				<meta name="keywords" content="Gurshan, Jhinger, Software, Engineer, Developer, SFU" />
				<link rel="icon" href="/logo.svg" />
			</Head>
			
			<Layout>
				<Component {...pageProps} /> 
			</Layout>
		</>
    )
}

export default MyApp
